### PR TITLE
Fix ``pytorch`` environment for package sync

### PR DESCRIPTION
**Pull request by jrbourbeau**
These are reasonable changes to make anyways, but I noticed this also fixes the package sync problem @scharlottej13 reported offline. @scharlottej13 can you see if the pytorch notebook now works for you? 

To be clear, I don't understand why this fixes things, but it seems to. We should figure out the issue folks are running into, but the changes here seem fine regardless.

### CODE REVIEW

**Comment by ntabris** [comment]
As in switching py3.10 to py3.11 fixes this?

**Comment by jrbourbeau** [comment]
Either that or dropping `pynvml` (which we automatically add now). I've not tried to reproduce the problem @scharlottej13 reported though on `main`.

**Comment by scharlottej13** [comment]
Thanks @jrbourbeau! Linking to the slack thread too: https://coiledcomputing.slack.com/archives/C064FUMHTSB/p1715887638735399

Confirming this solves my problem! Adding nvidia as a channel worked too.

**Comment by jrbourbeau** [comment]
> Confirming this solves my problem!

🎉 🤷

**Pull request merged**
