### PR TITLE
Add simple Spark notebook and environment

### PR DESCRIPTION
**Pull request by mrocklin**

### CODE REVIEW

**Review by jrbourbeau — APPROVED** [review]
Thanks @mrocklin. I've not actual run this notebook, but I've assumed you have and things work well (happy to run myself if you'd like).

My only comment, which is a non-blocking nit, is if the `dask.config.set({"dataframe.convert-string": True})` line is needed. Maybe an old version of Dask, where this isn't the default, is getting pulled in?

**Comment by jrbourbeau** [comment]
Actually, is that last cell needed at all? Is looks like it's just Dask, not Spark? Maybe this comes up in the talk-track?

**Comment by mrocklin** [comment]
Ah, thanks.  Fixed.

**Review by jrbourbeau — APPROVED** [review]
Thanks -- will merge after CI is done

**Pull request merged**
