### PR TITLE
Add datashader example

### PR DESCRIPTION
**Pull request by ncclementi**
- Adds separate env file
- Adds nb  with the interactive rendering of the pickup and dropoffs of 5 years of data

### CODE REVIEW

**Comment by mrocklin** [comment]
I've cleaned things up a little and (force) pushed.  This isn't doing interactive rendering for me just yet though.  Was that working for you?  Any thoughts?

**Comment by ncclementi** [comment]
Yes it was doing it perfectly, with no problem. I tried it even before pushing it.

**Comment by mrocklin** [comment]
Can I ask you to try with this one?  I'm curious if this is an environment issue.

**Comment by ncclementi** [comment]
Just making sure: did you click on the magnifier symbol on the right.? 
With my environment, I was able to run your updated notebook and it interacts
Kapture 2023-04-07 at 13 50 51

**Comment by mrocklin** [comment]
I removed some things from the environment, like JLab.  Are you running with that environment file or with the previous one that you made?

**Comment by ncclementi** [comment]
I'm running it with the one I had, were the only difference is Jlab and dask-lab-extension. Not sure why removing JLab from the env when you need it to launch the notebook

```yaml
name: datashader-demo
channels:
  - conda-forge
dependencies:
  - python==3.10
  - dask
  - coiled
  - pyarrow
  - ipykernel
  - dask-labextension==6.1.0
  - jupyterlab
  - s3fs
  - datashader
  - holoviews
  - hvplot
```

**Comment by mrocklin** [comment]
> Not sure why removing JLab from the env when you need it to launch the notebook

I'm running JupyterLab from my base environment, and using the kernel switcher to select different kernels.  This is useful, for example, if I'm running different notebooks with different environments (such as datashader kind of forces us to do).  I would prefer not to have multiple notebook servers running (although that's ok too).  

Maybe this helps a little bit with package sync times too.

**Comment by ncclementi** [comment]
Nat, Gabe, James, among other folks, tested the times of spinning up a cluster with and without JLab and there was pretty much no impact, I wouldn't worry about that.

**Pull request merged**
